# Generated by Django 3.2.13 on 2023-01-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_TeamWorkflows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffworkflow',
            name='item_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
